// <auto-generated />
using EduSpaceAllocator.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduSpaceAllocator.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918130544_AddAllocations")]
    partial class AddAllocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduSpaceAllocator.API.Models.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllocationId"));

                    b.Property<double>("CapacityUtilization")
                        .HasColumnType("double precision");

                    b.Property<double>("CostEfficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("MatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MatchScore")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimizationScore")
                        .HasColumnType("double precision");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<int>("SpaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("StudentReach")
                        .HasColumnType("double precision");

                    b.Property<int>("StudentsServed")
                        .HasColumnType("integer");

                    b.HasKey("AllocationId");

                    b.HasIndex("RequestId");

                    b.HasIndex("SpaceId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("EduSpaceAllocator.API.Models.Community", b =>
                {
                    b.Property<int>("CommunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommunityId"));

                    b.Property<string>("IncomeGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LiteracyRate")
                        .HasColumnType("double precision");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.HasKey("CommunityId");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("EduSpaceAllocator.API.Models.LearningRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PreferredLatitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PreferredLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PreferredLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentCapacity")
                        .HasColumnType("integer");

                    b.HasKey("RequestId");

                    b.HasIndex("CommunityId");

                    b.ToTable("LearningRequests");
                });

            modelBuilder.Entity("EduSpaceAllocator.API.Models.Space", b =>
                {
                    b.Property<int>("SpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpaceId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FloorArea")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<decimal>("RentalCost")
                        .HasColumnType("numeric");

                    b.HasKey("SpaceId");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("EduSpaceAllocator.API.Models.Allocation", b =>
                {
                    b.HasOne("EduSpaceAllocator.API.Models.LearningRequest", "LearningRequest")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduSpaceAllocator.API.Models.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningRequest");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("EduSpaceAllocator.API.Models.LearningRequest", b =>
                {
                    b.HasOne("EduSpaceAllocator.API.Models.Community", "Community")
                        .WithMany("LearningRequests")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("EduSpaceAllocator.API.Models.Community", b =>
                {
                    b.Navigation("LearningRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
